import { useEffect, useState } from "react"
import Head from "next/head"
import AppLayout from "components/AppLayout"
import Button from "components/Button"
import GitHub from "components/Icons/GitHub"
import { colors } from "styles/theme"

import { loginWithGithHub, onAuthStateChanged } from "../firebase/client"
import Avatar from "components/Avatar"

export default function Home() {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    onAuthStateChanged((user) => {
      setUser(user)
    })
  }, [])

  const handleClick = () => {
    loginWithGithHub().catch((err) => {
      console.log(err)
    })
  }

  return (
    <>
      <Head>
        <title>Alejo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/logo.png" alt="logo" />
          <h1>Devter</h1>
          <h2>
            Talk about development <br /> with developers
          </h2>

          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user && user.avatar && (
              <div>
                <Avatar
                  src={user.avatar}
                  alt={user.username}
                  text={user.username}
                />
              </div>
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        img {
          width: 120px;
        }

        div {
          margin-top: 16px;
        }

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        h1 {
          color: ${colors.primary};
          font-size: 24px;
          font-weight: 800;
          margin-bottom: 0;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 18px;
          margin: 0;
        }
      `}</style>
    </>
  )
}
