import { useEffect } from "react"

import Head from "next/head"

import Button from "components/Button"
import GitHub from "components/Icons/GitHub"

import { colors } from "styles/theme"

import { loginWithGithHub } from "../firebase/client"

import { useRouter } from "next/router"
import useUser, { USER_STATES } from "hooks/useUser"

export default function Home() {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGithHub().catch((err) => {
      console.log(err)
    })
  }

  return (
    <>
      <Head>
        <title>Alejo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <img src="/logo.png" alt="logo" />
        <h1>Devter</h1>
        <h2>
          Talk about development <br /> with developers
        </h2>

        <div>
          {user === USER_STATES.NOT_LOGGED && (
            <Button onClick={handleClick}>
              <GitHub fill="#fff" width={24} height={24} />
              Login with GitHub
            </Button>
          )}
          {user === USER_STATES.NOT_KNOWN && (
            <img src="/spinner.gif" alt="loading" />
          )}
        </div>
      </section>

      <style jsx>{`
        img {
          width: 120px;
        }

        div {
          margin-top: 16px;
        }

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        h1 {
          color: ${colors.primary};
          font-size: 24px;
          font-weight: 800;
          margin-bottom: 0;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 18px;
          margin: 0;
        }
      `}</style>
    </>
  )
}
